### ISSUE TITLE
英文例句的标点符号旁的单词点击偶尔出现

### ISSUE THREAD

**Issue by cervy** [burgessjp/GetWordTextView#2]
tv.getText().subSequence(tv.getSelectionStart(),// TODO: 取词  java.lang.StringIndexOutOfBoundsException: length=65; regionStart=-1; regionLength=0                                 tv.getSelectionEnd()).toString();

**Comment by guangzq** [comment]
我也遇到相同的问题
![image](https://cloud.githubusercontent.com/assets/19594348/22676966/e36c16b8-ed29-11e6-9636-b1f0e1a9d6c6.png)
